#!/bin/sh
cat \
    widgets/widgets.js \
	itemContainer.js \
	ajax.js \
	LoginController.js \
	grid.js \
	litGrid.js \
	hexGrid.js \
	rectGrid.js \
	persGrid.js \
	contentLayoutView.js \
	ACItemHandler.js \
	actions/GameAction.js \
	actions/ActionController.js \
	actions/ActionSummary.js \
	actions/HeightActionSummary.js \
	actions/SpeechActionSummary.js \
	actions/TeleportActionSummary.js \
	actions/MoveActionSummary.js \
	actions/ItemViewSelector.js \
	actions/ActionEditor.js \
	actions/SpeechActionEditor.js \
	actions/MoveActionEditor.js \
	actions/HeightActionEditor.js \
	actions/TeleportActionEditor.js \
	actions/actionViewWindow.js \
	conditions/GameCondition.js \
	conditions/ConditionSummary.js \
	conditions/TimestampConditionSummary.js \
	conditions/WeightConditionSummary.js \
	conditions/HasItemConditionSummary.js \
	conditions/ConditionEditor.js \
	conditions/TimestampConditionEditor.js \
	conditions/WeightConditionEditor.js \
	conditions/HasItemConditionEditor.js \
	SummaryItemDisplay.js \
	itemSelectorWindow.js \
	BlockItemWindow.js \
	ItemWindow.js \
	LightLevelWindow.js \
	EditWindow.js \
	TextEditWindow.js \
	AdminWindow.js \
	WorldChooserWindow.js \
	gameController.js \
	mapGame.js \
    > mw.js